#!/bin/bash
 
# AUTHOR:   (c) Rob W 2012
#           modified by MHC (http://askubuntu.com/users/81372/mhc)
#           and by Rodolfo Carvalho
# NAME:     GIFRecord 0.1-fedora
# DESCRIPTION:  A script to record GIF screencasts.
# LICENSE:  GNU GPL v3 (http://www.gnu.org/licenses/gpl.html)
# DEPENDENCIES:   byzanz,zenity,notify-send,slop

set -e

# Time and date
TIME=$(date +"%Y-%m-%d_%H%M%S")
 
# Standard screencast folder
GIF_DIR="$HOME/Pictures/byzanz"
 
# Sound notification to let one know when recording is about to start (and ends)
beep() {
    paplay /usr/share/sounds/freedesktop/stereo/message-new-instant.oga &
}
 
# Custom recording duration as set by user
OPTIONS=$(yad --form \
  --title "Byzanz" \
  --field "Screencast duration in seconds:":NUM 5 \
  --field "Delay before recording":NUM 2 \
  --field "Show mouse cursor":CHK TRUE \
  2>/dev/null)

# Recording duration
DURATION=$(awk -F '|' '{print $1}' <<< $OPTIONS)

# Delay before starting
DELAY=$(awk -F '|' '{print $2}' <<< $OPTIONS)
 
# Whether to show cursor in recording or not
SHOWCURSOR=$(awk -F '|' '{print $3}' <<< $OPTIONS)
 
# Window geometry
GEOMETRY=$(slop)
X=$(awk -F 'x|+' '{print $3}' <<< "$GEOMETRY")
Y=$(awk -F 'x|+' '{print $4}' <<< "$GEOMETRY")
W=$(awk -F 'x|+' '{print $1}' <<< "$GEOMETRY")
H=$(awk -F 'x|+' '{print $3}' <<< "$GEOMETRY")
 
# Notify the user of recording time and delay
notify-send "GIFRecorder" "Recording duration set to $DURATION seconds. Recording will start in $DELAY seconds."

if [ "$SHOWCURSOR" = TRUE ]; then
  SHOWCURSOR="-c"
else
  SHOWCURSOR=
fi

#Actual recording
sleep $DELAY
beep
byzanz-record -v $SHOWCURSOR --delay=0 -d $DURATION -x $X -y $Y -w $W -h $H "$GIF_DIR/GIFrecord_$TIME.gif"
beep
 
# Notify the user of end of recording.
notify-send "GIFRecorder" "Screencast saved to $GIF_DIR/GIFrecord_$TIME.gif"
